export const TICKET_STATUS_OPTIONS = Object.freeze([
  { value: "open", label: "Open", color: "info" },
  { value: "in_progress", label: "In progress", color: "warning" },
  { value: "waiting_on_customer", label: "Waiting on customer", color: "secondary" },
  { value: "resolved", label: "Resolved", color: "success" },
  { value: "closed", label: "Closed", color: "default" },
]);

export const TICKET_PRIORITY_OPTIONS = Object.freeze([
  { value: "low", label: "Low", color: "success" },
  { value: "medium", label: "Medium", color: "info" },
  { value: "high", label: "High", color: "warning" },
  { value: "urgent", label: "Urgent", color: "error" },
]);

export const TICKET_ISSUE_TYPE_OPTIONS = Object.freeze([
  { value: "access", label: "Access" },
  { value: "payroll", label: "Payroll" },
  { value: "leave", label: "Leave" },
  { value: "employee_profile", label: "Employee profile" },
  { value: "system", label: "System" },
]);

export const TICKET_FIELD_CONFIG = Object.freeze([
  {
    name: "reference",
    label: "Ticket number",
    type: "text",
    contexts: { list: true, detail: true, public: true },
    permissions: { read: "ticket:read" },
    grid: { xs: 12, md: 4 },
  },
  {
    name: "subject",
    label: "Subject",
    type: "text",
    required: true,
    placeholder: "Short summary of the request",
    contexts: { create: true, update: true, list: true, detail: true, public: true },
    permissions: { create: "ticket:create", update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12, md: 8 },
  },
  {
    name: "description",
    label: "Description",
    type: "textarea",
    required: true,
    placeholder: "Describe the issue, impact, and expected outcome",
    minRows: 4,
    contexts: { create: true, update: true, detail: true },
    permissions: { create: "ticket:create", update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12 },
  },
  {
    name: "issueType",
    label: "Issue type",
    type: "select",
    required: true,
    defaultValue: "system",
    options: TICKET_ISSUE_TYPE_OPTIONS,
    contexts: { create: true, update: true, list: true, detail: true, public: true },
    permissions: { create: "ticket:create", update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12, md: 4 },
  },
  {
    name: "priority",
    label: "Priority",
    type: "select",
    required: true,
    defaultValue: "medium",
    options: TICKET_PRIORITY_OPTIONS,
    contexts: { create: true, update: true, list: true, detail: true, public: true },
    permissions: { create: "ticket:create", update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12, md: 4 },
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    required: true,
    defaultValue: "open",
    options: TICKET_STATUS_OPTIONS,
    contexts: { update: true, list: true, detail: true, public: true },
    permissions: { update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12, md: 4 },
  },
  {
    name: "requesterName",
    label: "Requester name",
    type: "text",
    required: true,
    placeholder: "Employee or customer name",
    contexts: { create: true, update: true, list: true, detail: true, public: true },
    permissions: { create: "ticket:create", update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12, md: 4 },
  },
  {
    name: "requesterEmail",
    label: "Requester email",
    type: "email",
    required: true,
    placeholder: "requester@company.com",
    contexts: { create: true, update: true, detail: true },
    permissions: { create: "ticket:create", update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12, md: 4 },
  },
  {
    name: "requesterPhone",
    label: "Requester phone",
    type: "text",
    contexts: { create: true, update: true, detail: true },
    permissions: { create: "ticket:create", update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12, md: 4 },
  },
  {
    name: "organization",
    label: "Organization",
    type: "text",
    contexts: { create: true, update: true, list: true, detail: true },
    permissions: { create: "ticket:create", update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12, md: 4 },
  },
  {
    name: "department",
    label: "Department",
    type: "text",
    contexts: { create: true, update: true, list: true, detail: true },
    permissions: { create: "ticket:create", update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12, md: 4 },
  },
  {
    name: "assignee",
    label: "Assignee",
    type: "text",
    placeholder: "Agent or queue owner",
    contexts: { create: true, update: true, list: true, detail: true, public: true },
    permissions: { create: "ticket:assign", update: "ticket:assign", read: "ticket:read" },
    grid: { xs: 12, md: 4 },
  },
  {
    name: "dueDate",
    label: "Due date",
    type: "date",
    contexts: { create: true, update: true, detail: true },
    permissions: { create: "ticket:create", update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12, md: 4 },
  },
  {
    name: "resolutionNotes",
    label: "Resolution notes",
    type: "textarea",
    minRows: 3,
    contexts: { update: true, detail: true },
    permissions: { update: "ticket:update", read: "ticket:read" },
    grid: { xs: 12 },
  },
]);

export const TICKET_MODULE_CONFIG = Object.freeze({
  moduleId: "tickets",
  storage: {
    ticketsKey: "crm_hrms.tickets",
    sequenceKey: "crm_hrms.ticket_sequence",
  },
  ticketNumber: {
    prefix: "TKT",
    padding: 4,
  },
  permissions: {
    read: "ticket:read",
    create: "ticket:create",
    update: "ticket:update",
    assign: "ticket:assign",
    comment: "ticket:comment",
    attach: "ticket:attach",
  },
  labels: {
    notAvailable: "Not available",
    loading: "Loading ticket data...",
    backToTickets: "Back to tickets",
    notFound: "Ticket not found.",
  },
  create: {
    title: "Create ticket",
    description: "Capture a new support request with fields controlled by configuration.",
    submitLabel: "Create ticket",
    successMessage: "Ticket created successfully.",
    fields: [
      "subject",
      "description",
      "issueType",
      "priority",
      "requesterName",
      "requesterEmail",
      "requesterPhone",
      "organization",
      "department",
      "assignee",
      "dueDate",
    ],
  },
  list: {
    title: "Tickets",
    description: "Search, filter, sort, export, and inspect all tickets.",
    createAction: {
      label: "Create ticket",
      path: "/tickets/create",
      permission: "ticket:create",
    },
    emptyMessage: "No tickets found.",
    pageSizeOptions: [10, 25, 50],
    defaultPageSize: 10,
    columns: [
      { field: "reference", headerName: "Ticket #", width: 150 },
      { field: "subject", headerName: "Subject", flex: 1.2, minWidth: 220 },
      { field: "status", headerName: "Status", width: 160, presentation: "statusChip" },
      { field: "priority", headerName: "Priority", width: 130, presentation: "priorityChip" },
      { field: "issueType", headerName: "Issue type", width: 160, presentation: "optionLabel" },
      { field: "requesterName", headerName: "Requester", width: 180 },
      { field: "assignee", headerName: "Assignee", width: 180 },
      { field: "department", headerName: "Department", width: 160 },
      { field: "updatedAt", headerName: "Last updated", width: 180, presentation: "dateTime" },
      {
        field: "actions",
        type: "actions",
        headerName: "Actions",
        width: 90,
        permission: "ticket:read",
        actionLabel: "Open ticket",
      },
    ],
  },
  detail: {
    title: "Ticket lifecycle",
    description: "View the full activity trail and update ticket details.",
    fields: [
      "reference",
      "status",
      "priority",
      "issueType",
      "requesterName",
      "requesterEmail",
      "requesterPhone",
      "organization",
      "department",
      "assignee",
      "dueDate",
      "subject",
      "description",
      "resolutionNotes",
    ],
  },
  update: {
    title: "Update ticket details",
    submitLabel: "Save changes",
    successMessage: "Ticket details updated.",
    permission: "ticket:update",
    fields: [
      "subject",
      "description",
      "status",
      "priority",
      "issueType",
      "requesterName",
      "requesterEmail",
      "requesterPhone",
      "organization",
      "department",
      "assignee",
      "dueDate",
      "resolutionNotes",
    ],
  },
  comments: {
    title: "Comments",
    placeholder: "Add a comment for the ticket lifecycle",
    submitLabel: "Add comment",
    successMessage: "Comment added.",
    permission: "ticket:comment",
  },
  attachments: {
    title: "Attachments",
    selectLabel: "Select files",
    uploadLabel: "Add files",
    successMessage: "Files added.",
    permission: "ticket:attach",
  },
  lifecycle: {
    title: "Lifecycle",
    description: "A complete audit trail of creation, updates, comments, and attachments.",
    emptyMessage: "No lifecycle activity yet.",
    eventTypes: {
      created: { label: "Created", color: "success", public: true },
      updated: { label: "Updated", color: "info", public: true },
      commented: { label: "Commented", color: "secondary", public: false },
      attached: { label: "Attachment added", color: "warning", public: false },
    },
  },
  publicStatus: {
    title: "Check ticket status",
    description: "Enter a ticket number to view the current status without signing in.",
    submitLabel: "Check status",
    notFoundMessage: "No ticket matches that information.",
    lookupFields: [
      {
        name: "reference",
        label: "Ticket number",
        type: "text",
        required: true,
        placeholder: "TKT-2026-0001",
        grid: { xs: 12, md: 6 },
      },
      {
        name: "requesterEmail",
        label: "Requester email",
        type: "email",
        required: false,
        placeholder: "Optional",
        grid: { xs: 12, md: 6 },
      },
    ],
    visibleFields: [
      "reference",
      "subject",
      "status",
      "priority",
      "issueType",
      "requesterName",
      "assignee",
      "createdAt",
      "updatedAt",
    ],
  },
  mock: {
    tickets: [
      {
        id: "ticket-1",
        reference: "TKT-2026-0001",
        subject: "Unable to access employee self service",
        description: "Requester can sign in but the employee self service page returns a permission error.",
        issueType: "access",
        priority: "high",
        status: "in_progress",
        requesterName: "Aarav Sharma",
        requesterEmail: "aarav.sharma@example.com",
        requesterPhone: "+91 98765 43210",
        organization: "Acme India",
        department: "People Operations",
        assignee: "Support Desk",
        dueDate: "2026-08-21",
        resolutionNotes: "",
        createdAt: "2026-08-14T09:30:00.000Z",
        updatedAt: "2026-08-15T12:10:00.000Z",
        createdBy: { id: "agent-1", name: "Nisha Rao", email: "nisha.rao@example.com" },
        updatedBy: { id: "agent-2", name: "Kabir Mehta", email: "kabir.mehta@example.com" },
        comments: [
          {
            id: "comment-1",
            body: "Validated the requester role and escalated to identity management.",
            author: { id: "agent-2", name: "Kabir Mehta", email: "kabir.mehta@example.com" },
            createdAt: "2026-08-15T12:10:00.000Z",
          },
        ],
        attachments: [],
        lifecycle: [
          {
            id: "event-1",
            type: "created",
            actor: { id: "agent-1", name: "Nisha Rao", email: "nisha.rao@example.com" },
            createdAt: "2026-08-14T09:30:00.000Z",
            summary: "Ticket was created.",
          },
          {
            id: "event-2",
            type: "updated",
            actor: { id: "agent-2", name: "Kabir Mehta", email: "kabir.mehta@example.com" },
            createdAt: "2026-08-15T10:45:00.000Z",
            summary: "Ticket details were updated.",
            changes: [
              { field: "status", label: "Status", from: "open", to: "in_progress" },
              { field: "assignee", label: "Assignee", from: "Unassigned", to: "Support Desk" },
            ],
          },
          {
            id: "event-3",
            type: "commented",
            actor: { id: "agent-2", name: "Kabir Mehta", email: "kabir.mehta@example.com" },
            createdAt: "2026-08-15T12:10:00.000Z",
            summary: "Comment added.",
            comment: "Validated the requester role and escalated to identity management.",
          },
        ],
      },
      {
        id: "ticket-2",
        reference: "TKT-2026-0002",
        subject: "Payroll export mismatch for July",
        description: "Finance reported a mismatch between payroll export totals and approved payroll.",
        issueType: "payroll",
        priority: "urgent",
        status: "open",
        requesterName: "Maya Fernandes",
        requesterEmail: "maya.fernandes@example.com",
        requesterPhone: "+91 91234 56780",
        organization: "Acme India",
        department: "Finance",
        assignee: "",
        dueDate: "2026-08-19",
        resolutionNotes: "",
        createdAt: "2026-08-18T07:15:00.000Z",
        updatedAt: "2026-08-18T07:15:00.000Z",
        createdBy: { id: "agent-1", name: "Nisha Rao", email: "nisha.rao@example.com" },
        updatedBy: { id: "agent-1", name: "Nisha Rao", email: "nisha.rao@example.com" },
        comments: [],
        attachments: [],
        lifecycle: [
          {
            id: "event-4",
            type: "created",
            actor: { id: "agent-1", name: "Nisha Rao", email: "nisha.rao@example.com" },
            createdAt: "2026-08-18T07:15:00.000Z",
            summary: "Ticket was created.",
          },
        ],
      },
    ],
  },
});
