import ticketMetrics from "./metrics/ticketVolume.metrics.js";
import slaMetrics from "./metrics/sla.metrics.js";
import managementMetrics from "./metrics/management.metrics.js";
import professionalMetrics from "./metrics/professional.metrics.js";

const COMMON_TICKET_FILTERS = Object.freeze([
  "periodStart",
  "periodEnd",
  "departmentId",
  "organizationId",
  "assignedUserId",
  "priority",
  "severity",
  "category",
  "status",
]);

const METRIC_REGISTRY = Object.freeze([
  {
    code: "tickets.total",
    name: "Total Tickets",
    dashboardTypes: ["operational", "management", "executive"],
    permission: "ticket:read",
    description: "Tickets created within the selected reporting scope.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "ticketsTotal",
    drillDown: true,
  },
  {
    code: "tickets.open",
    name: "Open Tickets",
    dashboardTypes: ["operational", "management", "executive"],
    permission: "ticket:read",
    description: "Tickets currently in Open status within the selected scope.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "ticketsOpen",
    drillDown: true,
  },
  {
    code: "tickets.in_progress",
    name: "In Progress",
    dashboardTypes: ["operational", "management"],
    permission: "ticket:read",
    description: "Tickets currently in In Progress status.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "ticketsInProgress",
    drillDown: true,
  },
  {
    code: "tickets.waiting",
    name: "Waiting",
    dashboardTypes: ["operational", "management"],
    permission: "ticket:read",
    description: "Tickets currently waiting for response.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "ticketsWaiting",
    drillDown: true,
  },
  {
    code: "tickets.closed",
    name: "Closed Tickets",
    dashboardTypes: ["operational", "management", "executive"],
    permission: "ticket:read",
    description: "Tickets currently in Closed status.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "ticketsClosed",
    drillDown: true,
  },
  {
    code: "tickets.unassigned",
    name: "Unassigned Tickets",
    dashboardTypes: ["operational", "management"],
    permission: "ticket:read",
    description: "Tickets with no assigned user.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "ticketsUnassigned",
    drillDown: true,
  },
  {
    code: "tickets.my_open",
    name: "My Open Tickets",
    dashboardTypes: ["operational"],
    permission: "ticket:read",
    description: "Open tickets assigned to the authenticated user.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "myOpenTickets",
    drillDown: true,
  },
  {
    code: "tickets.status_distribution",
    name: "Ticket Status",
    dashboardTypes: ["operational", "management", "executive"],
    permission: "ticket:read",
    description: "Ticket distribution across statuses.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "donut",
    queryKey: "ticketStatusDistribution",
    drillDown: true,
  },
  {
    code: "tickets.severity_distribution",
    name: "Ticket Severity",
    dashboardTypes: ["operational", "management"],
    permission: "ticket:read",
    description: "Ticket distribution by severity.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "bar",
    queryKey: "severityDistribution",
    drillDown: true,
  },
  {
    code: "tickets.created_closed_trend",
    name: "Created vs Closed",
    dashboardTypes: ["operational", "management", "executive"],
    permission: "ticket:read",
    description: "Daily ticket creation and closure trend.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "line",
    queryKey: "createdClosedTrend",
    drillDown: false,
  },
  {
    code: "tickets.my_tickets",
    name: "My Tickets",
    dashboardTypes: ["operational"],
    permission: "ticket:read",
    description: "Recent tickets assigned to the authenticated user.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "table",
    queryKey: "myTickets",
    drillDown: true,
  },
  {
    code: "sla.running",
    name: "SLA Running",
    dashboardTypes: ["operational", "management", "professional", "executive"],
    permission: "sla:read",
    description: "Current SLA runtime records in RUNNING state.",
    timePeriod: "current",
    filters: ["periodStart", "periodEnd", "slaPolicyId", "slaStatus"],
    visualization: "kpi",
    queryKey: "running",
    drillDown: true,
  },
  {
    code: "sla.breached",
    name: "SLA Breached",
    dashboardTypes: ["operational", "management", "professional", "executive"],
    permission: "sla:read",
    description: "Current SLA runtime records in BREACHED state.",
    timePeriod: "current",
    filters: ["periodStart", "periodEnd", "slaPolicyId", "slaStatus"],
    visualization: "kpi",
    queryKey: "breached",
    drillDown: true,
  },
  {
    code: "sla.compliance",
    name: "SLA Compliance",
    dashboardTypes: [
      "operational",
      "management",
      "professional",
      "executive",
      "audit",
    ],
    permission: "sla:read",
    description:
      "Historical SLA compliance calculated from met and breached run history.",
    timePeriod: "activated_at",
    filters: ["periodStart", "periodEnd", "slaPolicyId", "slaStatus"],
    visualization: "kpi",
    queryKey: "compliance",
    drillDown: false,
  },
  {
    code: "sla.status_distribution",
    name: "SLA Status",
    dashboardTypes: ["operational", "management", "professional"],
    permission: "sla:read",
    description: "Current SLA runtime status distribution.",
    timePeriod: "current",
    filters: ["slaStatus"],
    visualization: "donut",
    queryKey: "slaStatusDistribution",
    drillDown: true,
  },
  {
    code: "sla.breach_distribution",
    name: "SLA Breaches by Policy",
    dashboardTypes: ["professional", "executive", "audit"],
    permission: "sla:read",
    description: "Historical SLA breach counts grouped by policy.",
    timePeriod: "activated_at",
    filters: ["periodStart", "periodEnd", "slaPolicyId", "slaStatus"],
    visualization: "bar",
    queryKey: "breachDistribution",
    drillDown: false,
  },
  {
    code: "tickets.my_created",
    name: "Created by Me",
    dashboardTypes: ["operational"],
    permission: "ticket:read",
    description: "Tickets created by the authenticated user.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "ticketsCreatedByMe",
    drillDown: true,
  },
  {
    code: "tickets.my_assigned",
    name: "Assigned to Me",
    dashboardTypes: ["operational"],
    permission: "ticket:read",
    description: "Tickets currently assigned to the authenticated user.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "ticketsAssignedToMe",
    drillDown: true,
  },
  {
    code: "tickets.my_in_progress",
    name: "My In Progress",
    dashboardTypes: ["operational"],
    permission: "ticket:read",
    description:
      "In-progress tickets currently assigned to the authenticated user.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "myInProgressTickets",
    drillDown: true,
  },
  {
    code: "tickets.my_waiting",
    name: "My Waiting",
    dashboardTypes: ["operational"],
    permission: "ticket:read",
    description:
      "Tickets waiting for response and currently assigned to the authenticated user.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "myWaitingTickets",
    drillDown: true,
  },
  {
    code: "tickets.my_closed",
    name: "My Closed Tickets",
    dashboardTypes: ["operational"],
    permission: "ticket:read",
    description: "Closed tickets currently assigned to the authenticated user.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "myClosedTickets",
    drillDown: true,
  },

  {
    code: "M001",
    name: "Service Performance Index",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description:
      "Composite service performance score based on SLA compliance and operational performance.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "servicePerformanceIndex",
    drillDown: false,
  },
  {
    code: "M002",
    name: "SLA Compliance %",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description:
      "Percentage of eligible SLA runs completed within the configured SLA target.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "slaCompliance",
    drillDown: false,
  },
  {
    code: "M003",
    name: "SLA Compliance Trend",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description:
      "Historical SLA compliance trend over the selected reporting period.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "line",
    queryKey: "slaComplianceTrend",
    drillDown: false,
  },
  {
    code: "M004",
    name: "SLA Breach Rate",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description:
      "Percentage of eligible SLA runs that breached their configured target.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "slaBreachRate",
    drillDown: false,
  },
  {
    code: "M005",
    name: "SLA Breach Trend",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description:
      "Historical SLA breach trend over the selected reporting period.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "line",
    queryKey: "slaBreachTrend",
    drillDown: false,
  },
  {
    code: "M006",
    name: "Average Resolution Time",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description: "Average resolution duration for completed SLA runs.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "averageResolutionTime",
    drillDown: false,
  },
  {
    code: "M007",
    name: "Median Resolution Time",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description: "Median resolution duration for completed SLA runs.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "medianResolutionTime",
    drillDown: false,
  },
  {
    code: "M008",
    name: "Resolution Time Variance",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description:
      "Distribution of resolution durations across completed SLA runs.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "histogram",
    queryKey: "resolutionTimeVariance",
    drillDown: false,
  },
  {
    code: "M009",
    name: "Target Achievement Rate",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description:
      "Percentage of completed SLA runs that achieved the configured target.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "targetAchievementRate",
    drillDown: false,
  },
  {
    code: "M010",
    name: "Maximum SLA Breach Duration",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description:
      "Maximum duration by which breached SLA runs exceeded their configured target.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "slaBreachDuration",
    drillDown: false,
  },
  {
    code: "M012",
    name: "Maximum Breach Duration",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description:
      "Maximum duration by which breached SLA runs exceeded their configured target.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "maximumBreachDuration",
    drillDown: false,
  },

  {
    code: "M011",
    name: "Average Breach Duration",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description:
      "Average duration by which breached SLA runs exceeded their target.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "averageBreachDuration",
    drillDown: false,
  },
  {
    code: "M014",
    name: "SLA Performance by Severity",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description: "SLA performance grouped by ticket severity.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "bar",
    queryKey: "slaPerformanceBySeverity",
    drillDown: false,
  },
  {
    code: "M017",
    name: "SLA Performance by Agent",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description: "SLA performance attributed to the current ticket assignee.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "bar",
    defaultView: "table",
    queryKey: "slaPerformanceByAgent",
    drillDown: false,
  },
  {
    code: "M023",
    name: "Backlog Aging Distribution",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description: "Distribution of currently open tickets by backlog age.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "bar",
    queryKey: "backlogAgingDistribution",
    drillDown: false,
  },
  {
    code: "M024",
    name: "Backlog Aging Risk",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description:
      "Percentage of the current backlog considered at risk due to aging.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "backlogAgingRisk",
    drillDown: false,
  },
  {
    code: "M025",
    name: "Long-Running Ticket Rate",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description:
      "Percentage of the current backlog classified as long-running.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "longRunningTicketRate",
    drillDown: false,
  },
  {
    code: "M029",
    name: "Service Demand by Category",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description: "Distribution of service demand across ticket categories.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "treemap",
    queryKey: "serviceDemandByCategory",
    drillDown: false,
  },
  {
    code: "M030",
    name: "Service Demand Trend",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description: "Ticket demand trend over the selected reporting period.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "line",
    queryKey: "serviceDemandTrend",
    drillDown: false,
  },
  {
    code: "M032",
    name: "Severity Mix",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description: "Distribution of tickets across severity levels.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "donut",
    queryKey: "severityMix",
    drillDown: false,
  },
  {
    code: "M033",
    name: "Department Service Performance",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description: "Service and SLA performance grouped by department.",
    timePeriod: "activated_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "bar",
    defaultView: "table",
    queryKey: "departmentServicePerformance",
    drillDown: false,
  },
  {
    code: "M037",
    name: "Throughput vs Demand",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description: "Comparison of ticket demand and ticket throughput over time.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "line",
    queryKey: "throughputVsDemand",
    drillDown: false,
  },
  {
    code: "M038",
    name: "Backlog Growth Rate",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description:
      "Change in backlog between the latest and preceding reporting points.",
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "backlogGrowthRate",
    drillDown: false,
  },
  {
    code: "M039",
    name: "Service Capacity Utilization",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description:
      "Service capacity utilization based on the configured capacity model.",
    timePeriod: "current",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "serviceCapacityUtilization",
    drillDown: false,
  },
  {
    code: "M040",
    name: "Workload Concentration",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description:
      "Share of open assigned workload concentrated among the highest-workload agents.",
    timePeriod: "current",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "workloadConcentration",
    drillDown: false,
  },
  {
    code: "M041",
    name: "High-Risk Ticket Exposure",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description: "Number of currently open tickets classified as high risk.",
    timePeriod: "current",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "highRiskTicketExposure",
    drillDown: false,
  },
  {
    code: "M042",
    name: "Open Critical Exposure",
    dashboardTypes: ["management"],
    permission: "ticket:read",
    description: "Number of currently open critical-severity tickets.",
    timePeriod: "current",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "openCriticalExposure",
    drillDown: false,
  },
  {
    code: "M043",
    name: "SLA Risk Exposure",
    dashboardTypes: ["management"],
    permission: "sla:read",
    description:
      "Number of running SLA records currently within the configured risk threshold.",
    timePeriod: "current",
    filters: COMMON_TICKET_FILTERS,
    visualization: "kpi",
    queryKey: "slaRiskExposure",
    drillDown: false,
  },

  ...[
    ["P001", "Service Type Wise", "serviceType"],
    ["P002", "District Wise", "district"],
    ["P003", "Department Wise", "department"],
    ["P004", "Category Wise", "category"],
    ["P005", "Problem Statement Wise", "problemStatement"],
    ["P006", "Current Bill Status Wise", "currentBillStatus"],
    ["P007", "Status Wise", "status"],
    ["P008", "Assigned To Wise", "assignedTo"],
    ["P009", "Severity Wise", "severity"],
    ["P010", "Dependency Category Wise", "dependencyCategory"],
    ["P011", "Issue Category Wise", "issueCategory"],
    ["P012", "Created By Wise", "createdBy"],
  ].map(([code, name, queryKey]) => ({
    code,
    name,
    dashboardTypes: ["professional"],
    permission: "ticket:read",
    description: `${name} ticket distribution.`,
    timePeriod: "created_at",
    filters: COMMON_TICKET_FILTERS,
    visualization: "bar",
    queryKey,
    drillDown: true,
  })),
]);

const HANDLERS = Object.freeze({
  ...ticketMetrics,
  ...slaMetrics,
  ...managementMetrics,
  ...professionalMetrics,
});

export function getMetricRegistry() {
  return METRIC_REGISTRY;
}

export function getMetric(metricCode) {
  return METRIC_REGISTRY.find((metric) => metric.code === metricCode) || null;
}

export function getMetricsForDashboard(dashboardType) {
  return METRIC_REGISTRY.filter((metric) =>
    metric.dashboardTypes.includes(dashboardType),
  );
}

function getMetricExplanation(definition) {
  return {
    calculation: definition?.calculation ?? null,
    interpretation: definition?.interpretation ?? null,
    dataSource: definition?.dataSource ?? null,
  };
}

export async function executeMetric(metricCode, context) {
  const definition = getMetric(metricCode);
  if (!definition) {
    return null;
  }

  const handler = HANDLERS[definition.queryKey];
  if (!handler) {
    throw new Error(
      `Metric handler '${definition.queryKey}' is not registered.`,
    );
  }

  const result = await handler(context);

  const isKpi = definition.visualization === "kpi";

  const viewModes =
    definition.viewModes ??
    (isKpi
      ? ["kpi"]
      : definition.visualization === "table"
        ? ["table"]
        : ["graph", "table"]);

  const defaultView =
    definition.defaultView ??
    (isKpi ? "kpi" : definition.visualization === "table" ? "table" : "graph");
  const explanation = getMetricExplanation(definition);
  return {
    ...result,
    viewModes,
    defaultView,
    metadata: {
      ...(result.metadata || {}),
      definition: {
        code: definition.code,
        description: definition.description,
        filters: definition.filters,
        timePeriod: definition.timePeriod,
        visualization: definition.visualization,
        viewModes,
        defaultView,
        calculation: explanation.calculation,
        interpretation: explanation.interpretation,
        dataSource: explanation.dataSource,
      },
    },
  };
}

export default Object.freeze({
  getMetricRegistry,
  getMetric,
  getMetricsForDashboard,
  executeMetric,
});
