import { heading, keyValueTable } from "../reportPdf.styles.js";

export function renderDocumentControl(doc, data) {
  heading(doc, "2. Document Control");
  const c = data.documentControl;
  keyValueTable(doc, [
    ["Report ID", c.reportId],
    ["Report Type", c.reportType],
    ["Report Version", c.reportVersion],
    ["Calculation Version", c.calculationVersion],
    ["Reporting Period", `${c.periodStart} → ${c.periodEnd}`],
    ["Data Cut-off", c.dataCutoff],
    ["Generated At", c.generatedAt],
    ["Generated By", c.generatedByUserId || "System"],
    ["Timezone", c.timezone],
    ["Status", c.status],
    ["Record Count", c.recordCount],
  ]);
}
